export const STATUS_MAP = {
  searching: ["Searching suppliers", "info"],
  quotes_received: ["Quotes received", "info"],
  negotiation: ["In negotiation", "warn"],
  order_confirmed: ["Order confirmed", "ok"],
  production: ["In production", "warn"],
  inspection: ["Quality inspection", "warn"],
  shipping: ["Shipping", "info"],
  customs: ["Customs clearance", "info"],
  delivered: ["Delivered", "ok"],
  secured: ["Payment secured", "ok"],
  held: ["Payment confirmed", "warn"],
  released: ["Released to supplier", "ok"],
  refunded: ["Refunded to buyer", "info"],
  pending: ["Pending", "warn"],
  approved: ["Approved", "ok"],
  rejected: ["Rejected", "danger"],
  investigating: ["Investigating", "warn"],
  awaiting_supplier: ["Awaiting supplier", "warn"],
  resolved: ["Resolved", "ok"],
  document_review: ["Document review", "info"],
  remote_factory_check: ["Remote factory check", "info"],
  background_check: ["Background check", "info"],
  not_submitted: ["Not submitted", "danger"],
  unverified: ["Unverified", "neutral"],
  verified: ["Verified", "info"],
  gold: ["Gold", "warn"],
  platinum: ["Platinum", "ok"],
  open: ["Open", "warn"],
  escalated: ["Escalated", "danger"],
  closed: ["Closed", "ok"],
  SUPPLIER_APPLICATION_STARTED: ["Draft", "neutral"],
  SUPPLIER_VERIFICATION_PENDING: ["Pending review", "warn"],
  SUPPLIER_VERIFIED: ["Verified", "ok"],
  SUPPLIER_REJECTED: ["Rejected", "danger"],
  SUPPLIER_RESTRICTED: ["Restricted", "danger"],
  SUPPLIER_SUSPENDED: ["Suspended", "danger"],
  BUYER_VERIFICATION_PENDING: ["Pending review", "warn"],
  BUYER_VERIFIED: ["Verified", "ok"],
  BUYER_REJECTED: ["Rejected", "danger"],
};
